# Generated by Django 4.2.3 on 2023-07-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="order_id",
            field=models.IntegerField(default=-1),
        ),
    ]
