# Generated by Django 4.2.3 on 2023-07-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="order_id",
            field=models.IntegerField(default=-1, help_text="(The order ID of the last open Order)"),
        ),
    ]
