# Generated by Django 4.2.3 on 2023-07-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0004_alter_order_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColourVariation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="SizeVariation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
            ],
        ),
    ]
