# Generated by Django 4.2.3 on 2023-07-11 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0005_colourvariation_sizevariation"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ColourVariation",
            new_name="ColorVariation",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="color",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="cart.colorvariation"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="size",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="cart.sizevariation"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="color_variation",
            field=models.ManyToManyField(to="cart.colorvariation"),
        ),
        migrations.AddField(
            model_name="product",
            name="size_variation",
            field=models.ManyToManyField(to="cart.sizevariation"),
        ),
    ]
