# Generated by Django 4.2.3 on 2023-07-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0006_rename_colourvariation_colorvariation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
