# Generated by Django 4.2.3 on 2023-07-12 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0009_alter_address_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="address_type",
        ),
        migrations.AlterField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
